# Generated by Django 4.1.7 on 2023-03-27 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ship_status', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='product_id',
            new_name='roduct_id',
        ),
    ]
