# Generated by Django 4.1.7 on 2023-03-27 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ship_status', '0002_rename_product_id_shipment_roduct_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='roduct_id',
            new_name='product_id',
        ),
    ]
